/**
 * Baked PBR texture sets, loaded once and shared by every material.
 *
 * The images in /public/textures are generated by scripts/textures/bake.py from
 * seeded procedural noise — no third-party assets, reproducible byte for byte.
 * Each set is three maps (see the bake script for the channel layout):
 *
 *   normal  tangent-space normal, OpenGL convention
 *   orm     R cavity AO · G relative roughness · B albedo detail
 *   wear    R rust · G grime · B chipped paint
 *
 * Materials never wait for an image: every sampler starts on a neutral 1×1
 * placeholder and is swapped for the real texture when it arrives. Because the
 * uniform objects are shared, one swap updates every material using the set.
 */

import * as THREE from 'three';
import type { TextureSetName } from '../materials';

/** Physical size of one texture tile, in metres. Must match bake.py. */
export const TEXTURE_TILE_METRES: Record<TextureSetName | 'water' | 'foam', number> = {
  hull: 9.6,
  deck: 4.8,
  paint: 1.6,
  metal: 1.0,
  water: 24.0,
  foam: 6.0,
};

export type TextureResolution = 'full' | 'reduced';

export interface TextureSetUniforms {
  readonly normal: THREE.IUniform<THREE.Texture>;
  readonly orm: THREE.IUniform<THREE.Texture>;
  readonly wear: THREE.IUniform<THREE.Texture>;
  readonly scale: THREE.IUniform<number>;
}

const BASE_PATH = '/textures';

function neutral(r: number, g: number, b: number): THREE.DataTexture {
  const texture = new THREE.DataTexture(new Uint8Array([r, g, b, 255]), 1, 1);
  texture.wrapS = THREE.RepeatWrapping;
  texture.wrapT = THREE.RepeatWrapping;
  texture.needsUpdate = true;
  return texture;
}

/** Flat normal, mid roughness, full albedo, no wear. */
const PLACEHOLDERS = {
  normal: neutral(128, 128, 255),
  orm: neutral(255, 128, 235),
  wear: neutral(0, 0, 0),
};

/** Neutral stand-ins for textures that are still loading. */
export const FLAT_NORMAL: THREE.Texture = PLACEHOLDERS.normal;
export const NO_FOAM: THREE.Texture = PLACEHOLDERS.wear;

const sets = new Map<TextureSetName, TextureSetUniforms>();
const loaded = new Map<string, THREE.Texture>();
let maxAnisotropy = 8;
let resolution: TextureResolution = 'full';
let loader: THREE.TextureLoader | null = null;

/** Only the hull set ships a reduced variant; the others are already 1K. */
const HAS_REDUCED: ReadonlySet<TextureSetName> = new Set(['hull']);

function fileFor(set: TextureSetName, map: 'normal' | 'orm' | 'wear'): string {
  const suffix = resolution === 'reduced' && HAS_REDUCED.has(set) ? '_1k' : '';
  return `${BASE_PATH}/${set}_${map}${suffix}.webp`;
}

/**
 * Loads (or reuses) an image as a repeating data texture. Data maps must stay
 * linear: tagging them sRGB would bend every normal and roughness value.
 */
export function loadDataTexture(url: string, onReady: (texture: THREE.Texture) => void): void {
  const cached = loaded.get(url);
  if (cached) {
    onReady(cached);
    return;
  }
  loader ??= new THREE.TextureLoader();
  loader.load(
    url,
    (texture) => {
      texture.wrapS = THREE.RepeatWrapping;
      texture.wrapT = THREE.RepeatWrapping;
      texture.colorSpace = THREE.NoColorSpace;
      texture.anisotropy = maxAnisotropy;
      texture.generateMipmaps = true;
      texture.minFilter = THREE.LinearMipmapLinearFilter;
      texture.needsUpdate = true;
      loaded.set(url, texture);
      onReady(texture);
    },
    undefined,
    () => {
      // A missing texture degrades to the flat placeholder — the scene still
      // renders, just without micro-detail. Worth a warning, not a crash.
      console.warn(`[DryDock] texture failed to load: ${url}`);
    },
  );
}

function requestSet(set: TextureSetName, uniforms: TextureSetUniforms): void {
  for (const map of ['normal', 'orm', 'wear'] as const) {
    const url = fileFor(set, map);
    loadDataTexture(url, (texture) => {
      // A slower load for a resolution the user has since switched away from
      // must not overwrite the one now wanted.
      if (fileFor(set, map) !== url) return;
      const previous = uniforms[map].value;
      uniforms[map].value = texture;
      releaseUnused(previous);
    });
  }
}

/**
 * Frees a texture swapped out by a resolution change (the 2K hull maps when
 * stepping down), unless some set still uses it or it is a placeholder. It is
 * reloaded from the HTTP cache if the user steps back up.
 */
function releaseUnused(texture: THREE.Texture): void {
  if (Object.values(PLACEHOLDERS).includes(texture as THREE.DataTexture)) return;
  for (const uniforms of sets.values()) {
    if (uniforms.normal.value === texture || uniforms.orm.value === texture || uniforms.wear.value === texture) return;
  }
  for (const [url, cached] of loaded) {
    if (cached === texture) loaded.delete(url);
  }
  texture.dispose();
}

/** Shared uniforms for a texture set. Loading starts on first request. */
export function getTextureSet(set: TextureSetName): TextureSetUniforms {
  const existing = sets.get(set);
  if (existing) return existing;

  const uniforms: TextureSetUniforms = {
    normal: { value: PLACEHOLDERS.normal },
    orm: { value: PLACEHOLDERS.orm },
    wear: { value: PLACEHOLDERS.wear },
    scale: { value: 1 / TEXTURE_TILE_METRES[set] },
  };
  sets.set(set, uniforms);
  if (typeof window !== 'undefined') requestSet(set, uniforms);
  return uniforms;
}

/**
 * Tells the texture system what the renderer can do and how much memory the
 * current quality profile allows. Safe to call repeatedly; only a change of
 * resolution triggers any loading.
 */
export function configureTextures(renderer: THREE.WebGLRenderer, next: TextureResolution): void {
  const anisotropy = Math.min(16, renderer.capabilities.getMaxAnisotropy());
  if (anisotropy !== maxAnisotropy) {
    maxAnisotropy = anisotropy;
    for (const texture of loaded.values()) {
      texture.anisotropy = anisotropy;
      texture.needsUpdate = true;
    }
  }

  if (next === resolution) return;
  resolution = next;
  for (const [name, uniforms] of sets) {
    if (HAS_REDUCED.has(name)) requestSet(name, uniforms);
  }
}
